-- Animee AI knowledge base
-- Run once in the Supabase SQL Editor for project mnfzpbwhvierboadwctz.

create table if not exists public.ai_knowledge (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 160),
  category text not null default 'Other',
  content text not null check (char_length(content) between 1 and 5000),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.ai_knowledge enable row level security;

drop policy if exists "Anyone can read active Animee AI knowledge" on public.ai_knowledge;
create policy "Anyone can read active Animee AI knowledge"
  on public.ai_knowledge for select to anon, authenticated
  using (is_active = true);

drop policy if exists "Animee owner can manage AI knowledge" on public.ai_knowledge;
create policy "Animee owner can manage AI knowledge"
  on public.ai_knowledge for all to authenticated
  using (auth.uid() = '991aadfe-375e-41b1-b709-a4e0cbf74512'::uuid)
  with check (auth.uid() = '991aadfe-375e-41b1-b709-a4e0cbf74512'::uuid);

grant select on public.ai_knowledge to anon, authenticated;
grant insert, update, delete on public.ai_knowledge to authenticated;
grant usage, select on sequence public.ai_knowledge_id_seq to authenticated;
