-- Animee AI knowledge base
-- Run once in the Supabase SQL Editor for project mnfzpbwhvierboadwctz.

create table if not exists public.ai_knowledge (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 160),
  category text not null default 'Other',
  content text not null check (char_length(content) between 1 and 5000),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.ai_knowledge enable row level security;

drop policy if exists "Anyone can read active Animee AI knowledge" on public.ai_knowledge;
create policy "Anyone can read active Animee AI knowledge"
  on public.ai_knowledge for select to anon, authenticated
  using (is_active = true);

drop policy if exists "Animee owner can manage AI knowledge" on public.ai_knowledge;
create policy "Animee owner can manage AI knowledge"
  on public.ai_knowledge for all to authenticated
  using (auth.uid() = '991aadfe-375e-41b1-b709-a4e0cbf74512'::uuid)
  with check (auth.uid() = '991aadfe-375e-41b1-b709-a4e0cbf74512'::uuid);

grant select on public.ai_knowledge to anon, authenticated;
grant insert, update, delete on public.ai_knowledge to authenticated;
grant usage, select on sequence public.ai_knowledge_id_seq to authenticated;

-- Seed a few verified basics so Animee AI knows the official page after setup.
insert into public.ai_knowledge (title, category, content, is_active)
select 'Official Animee Facebook page', 'Social links',
       'The official Facebook page is https://www.facebook.com/animeeeeee/. When users ask for Animee Facebook, direct them to this URL.',
       true
where not exists (select 1 from public.ai_knowledge where title = 'Official Animee Facebook page');

insert into public.ai_knowledge (title, category, content, is_active)
select 'Animee brand and tagline', 'Animee brand',
       'The page name is Animee. The brand tagline is “Animee — Where Anime Comes to Life.” Use the spelling Animee, not Animeee or Animee Zone, unless the owner explicitly changes it.',
       true
where not exists (select 1 from public.ai_knowledge where title = 'Animee brand and tagline');

insert into public.ai_knowledge (title, category, content, is_active)
select 'Animee posting schedule', 'Posting schedule',
       'The owner currently schedules Facebook Reels at 7 AM, 3 PM, and 11 PM Philippines time. If asked about the schedule, mention that these are the current planned posting times and may change.',
       true
where not exists (select 1 from public.ai_knowledge where title = 'Animee posting schedule');

insert into public.ai_knowledge (title, category, content, is_active)
select 'Official Animee Instagram', 'Social links',
       'The official Instagram profile is https://www.instagram.com/animee.media/.',
       true
where not exists (select 1 from public.ai_knowledge where title = 'Official Animee Instagram');

